import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');

const read = file =>
  readFile(path.join(root, file), 'utf8');

const html = await read('manager.html');
const page = await read('pages/manager-page.js');
const tabs = await read('components/manager-tabs.js');
const print = await read('manager-memo-print.js');
const wardPrint = await read('ward-print.js');
const ops = await read('pages/manager-night-operations.js');


test('Manager has four source-defined primary workspaces in requested order', () => {
  const names = [...html.matchAll(/data-manager-tab="([^"]+)"/g)]
    .map(match => match[1]);

  assert.deepEqual(
    names.slice(0, 4),
    ['submission', 'ward-info', 'memo', 'staffing']
  );

  assert.match(html, />Submission Status</);
  assert.match(html, />Ward Information</);
  assert.match(html, />Night Memo</);
  assert.match(html, />Night Staffing</);
  assert.doesNotMatch(html, /onclick=/i);
});


test('Official Night Memo editor excludes Ward information fields', () => {
  assert.doesNotMatch(
    html,
    /id="memoClinicalNotes"|id="memoAdditionalItems"/
  );

  assert.doesNotMatch(
    print,
    /Clinical \/ General Notes|Additional Report Items/
  );

  // Legacy fields may exist only for migration cleanup.
  assert.match(
    page,
    /clinicalNotesHtml: _legacyClinical/
  );

  assert.match(
    page,
    /additionalItemsHtml: _legacyAdditional/
  );
});


test('Ward Information is generated by the source-owned renderer', () => {
  assert.match(
    html,
    /id="wardInformationList"/
  );

  assert.match(
    page,
    /buildManagerWardInformation/
  );

  assert.match(
    page,
    /Patient List/
  );

  assert.match(
    page,
    /Consultation/
  );

  assert.match(
    page,
    /Intubation/
  );

  assert.match(
    page,
    /Additional Report Items/
  );

  const panel =
    html.match(
      /data-manager-tab-panel="ward-info"[^]*?<\/section>\s*<\/section>/
    )?.[0] || '';

  assert.doesNotMatch(
    panel,
    /contenteditable="true"/
  );
});


test('Manager reuses Ward paper renderer', () => {
  assert.match(
    page,
    /import\('\.\.\/ward-print\.js'\)/
  );

  assert.match(
    page,
    /writeWardMemoToIframe/
  );

  assert.match(
    page,
    /printWardMemo/
  );

  assert.match(
    html,
    /id="wardMemoPreviewFrame"/
  );

  assert.match(
    wardPrint,
    /export function renderWardMemoHtml/
  );

  assert.doesNotMatch(
    page,
    /renderFullReport/
  );
});


test('Night Staffing is a source-defined tab', () => {
  assert.match(html, /id="nightWardStaffRows"/);
  assert.match(html, /id="nightRunnerRows"/);

  assert.doesNotMatch(
    html,
    /nightWardListDisclosure|nightRunnerListDisclosure/
  );

  assert.match(
    ops,
    /nightWardStaffRows/
  );

  assert.match(
    ops,
    /nightRunnerRows/
  );
});


test('Manager tabs own navigation state', () => {
  assert.match(
    tabs,
    /ArrowLeft/
  );

  assert.match(
    tabs,
    /aria-selected/
  );

  assert.match(
    page,
    /managerTabs\?\.setEnabled\(false\)/
  );

  assert.match(
    page,
    /managerTabs\?\.setEnabled\(true\)/
  );
});